language: rust
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo libatasmart | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: L3oertPwahXDjaugaVyCmyVPZwieOIgBiGKYH4NlbJRQjTltHnY6RErD1fm/MXL0wUEWeKv6PaJh17re2bMo58NwzBOrIqvIL2WYoetApJIPNtLC12CX7RMsGqELP7SszR7+HXUtswX1hpAAQGX7p/IOSjJx6VhQwyIUQY/7tD9iAn0w8Z7iZ/iKvLZXj2Kp8UpPOaAVOt87fdQzq6QnriBYQ2svaapNBPs4VHL0CDX7B06WlaaNMMUgXLoOZRQ10BtYrGS4RMbxey0sCezL6Gf/gWBtE7kpyQqIwLe5Yh4XMIMEOyqLxkKBCw1b4FZrIUNMi4HIQYYla56H10B/6rhz9A00YYtFKbCENRKJqeuwXvi4GCcfWsZ8egLVBzvBQCR4gP7cLwupejZe5iZY50pfB5/PZ4+f1uDmBJr/vZBaUjl3br/G/vqJtsKzmWGfRhc7gFmVH6D6+pY18JMATCvIz9WpCIPR7etEatoUWwSLk/y7ZLu2FVkP2GvypSuRpIaZGV6HyhLoffRrKX4bF7YT16pJQRoaGW6biPE1PDEbVW6o9HHsoM6n8oGcWYMWb54c/Ea15iZ5/HykUfP3dNE4sVhoQPfZslpGZYjuAcL0cXS+t7sx9i1ZfGE8hMjIABmoZvG02OJSZJ9Bzysy+ARCts0J/oNSIVyQzLE40kc=
